### ISSUE TITLE
[Question] Is it possible to get this to work in one file?

### ISSUE THREAD

**Issue by Wowfunhappy** [bentasker/RemoveAMP#1]
Hello!

I'm trying to get this userscript to work on Jailbroken iOS, and the setup I'm using doesn't appear to support the `require` field. Is it possible to get the entire thing in one user.js file, without the external resource?

I attempted to add the contents of https://static1.bentasker.co.uk/adblock/anti-amp/v1.3.js into the main userscript file directly, which seemed like it should work but completely didn't. I don't know much about userscripts, so I assume  there's a mechanism here I'm not understanding... if you could provide any pointers at all, it would be greatly appreciated.

Thank you!

**Comment by bentasker** [comment]
Hi,

> Is it possible to get the entire thing in one user.js file, without the external resource?

possibly, but we might also be able to get it working for you using and older version of the greasemonkey script.

The caveat with that though, is that it won't work where the site specifies a Content-Security-Policy (CSP), which is why I changed it to use `require` in the first place.

Try using this version of the file - https://github.com/bentasker/RemoveAMP/blob/cb974e1bf7302233d32d64eaf1a11aca98d82180/greasemonkey_hook.user.js

and see if that works for you. Rather than using `require` it'll write a `script` tag into the document head.

That said, I've just had a tinker, and I suspect I know why your attempts haven't worked.

This works for me on my test page:
```
// ==UserScript==
// @name         New Userscript
// @namespace    http
// @version      0.1
// @description  try to take over the world!
// @author       You
// @match        https://projectsstatic.bentasker.co.uk/MISC/MISC25/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

function fuckOffAMP(){
    // Check whether it's AMP html
    var h = document.getElementsByTagName('html');
    if (h[0].getAttribute('amp') != null || h[0].getAttribute('⚡') != null){
        console.log("eww vile... trying to redirect");


        // Try and find a canonical link
        eles = document.getElementsByTagName('link');
        for (var i=0; i<eles.length;i++){
            if (eles[i].getAttribute('rel') == 'canonical' && eles[i].getAttribute('rel') != window.location.href.split('#')[0]){
                window.location.href = eles[i].getAttribute('href');
                console.log("Redirecting you");
                return;
            }
        }

        // If we got this far, there's no canonical :(
        console.log("Sorry, but you're stuck with the sucky version of this page. Maybe search for the proper version?");

        // Build a link to search DuckDuckGo for the page title (to hopefully find the proper version)
        t = document.getElementsByTagName('title')[0];
        qs = encodeURIComponent(t.innerHTML);
        searchurl = 'https://duckduckgo.com/?t=hg&ia=web&q='+qs

        altlink = document.createElement('a');
        altlink.href = searchurl;
        altlink.title = 'Try and find a proper verison of this page';
        altlink.innerHTML = 'Search for a non-AMP version of this page';

        // Drop the link in at the top
        document.body.insertBefore(altlink, document.body.firstChild);
    }else{
        console.log("Doesn't appear to be AMP'd");
    }

}


var b = document.getElementsByTagName('body')[0];
var s = document.createElement('script');
s.setAttribute('type','text/javascript');
s.appendChild(document.createTextNode('('+ fuckOffAMP +')();'))
b.appendChild(s);

})();
```

When I created that to test, it didn't work at first, and I suspect you've been tripped up by the same thing I was.

Did you view https://static1.bentasker.co.uk/adblock/anti-amp/v1.3.js in your browser and copy from there? If so, is the lightning bolt showing in the second check, or does it look like this (I'm *really* hoping Github is going to render this properly.

```
if (h[0].getAttribute('amp') != null || h[0].getAttribute('âš¡') != null){
```
If so, that'll have broken your script. Replace that by pasting in the lightning bolt (you can go to https://projectsstatic.bentasker.co.uk/MISC/MISC25/bad.html and view source - it's in the `<html` tag)

Once I fixed that, the version I've put above works for me

**Comment by Wowfunhappy** [comment]
Thank you so much! Yes, it looks like I was getting screwed up by `âš¡`!
