### ISSUE TITLE
Not working with links from Google Search?

### ISSUE THREAD

**Issue by Wowfunhappy** [bentasker/RemoveAMP#2]
I'm still having some trouble with this!

I am testing the [official version of the script](https://github.com/bentasker/RemoveAMP/raw/master/greasemonkey_hook.user.js) in desktop Safari 12.1.1, with the Tapermonkey extension. However, I'm also using an iPhone user agent, so that Google Search will try to serve me AMP pages. (My ultimate goal is to use this on iOS, but I'm testing on Mac to isolate the issue.)

Although the userscript works on the [AMP test page](https://projectsstatic.bentasker.co.uk/MISC/MISC25/bad.html), it's not working with Google search results.

Here are some example URLs from Google where I'm not being redirected:
https://www.google.com/amp/s/www.theregister.co.uk/AMP/2017/05/19/open_source_insider_google_amp_bad_bad_bad/
https://www.google.com/amp/s/www.theverge.com/platform/amp/2019/4/16/18402628/google-amp-url-problem-signed-exchange-original-chrome-cloudflare
https://www.google.com/amp/s/www.wired.com/2016/02/googles-amp-speeding-web-changing-works/winamp/

Remember to use a mobile user agent when viewing these URLs—otherwise, Google will automatically redirect you, even without the userscript. For reference, the exact user agent I'm testing with is `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1`

Any ideas? Thanks again!

**Comment by bentasker** [comment]
OK, got to the bottom of this (commit inbound, and then I'll update the copy hosted on my CDN).

So, if you look at what Google actually return, you'll get a whole load of markup on one line (with some very obfuscated javascript), but crucially, this is how it opens
```
<!doctype html><html lang="en-GB" jsl="$t t-KQGreKEI5HU;$x 0;" class="r-iaKt_mpAHihk">
```

Note the lack of lightning symbol, or `amp` attribute. Google aren't actually declaring these pages as AMP (which doesn't align with the requirements here - https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml?referrer=ampproject.org#ampd). 

What this means is when the script checks if the page is AMP'd, it decides it isn't (because it isn't compliant with the requirements of the published AMP specs)

It's dirty, and I don't particularly like it, but the script will now assume that everything under "https://www.google.com/amp/s/" is AMP and treat it as such.

**Comment by bentasker** [comment]
It does seem to do a couple of page repaints/reloads before ending up on the canonical though - may need to look into that when I'm more awake.

**Comment by Wowfunhappy** [comment]
It *almost* works! The only remaining problem is I have to manually reload the page before I'm redirected.

Instead of using the links directly, try searching something on Google and then clicking on an AMP search result.

**Comment by bentasker** [comment]
I've had a few runs at it, but unfortunately (arguably, fortunately), Google's search won't serve me AMP urls regardless of my user-agent, so I can't have a look to try and resolve it.

Are you able to reproduce with Curl? Or perhaps get a screen shot of view-source on whatever page it's landing you on (console output would be handy too, in case something's killing the script)

Could you paste the URL it's stuck on too (though I assume it's probably the same as the ones listed earlier)

**Comment by Wowfunhappy** [comment]
I'm quite surprised you can't get AMP pages with an iOS user agent, I did a test in Firefox on Windows and it worked there too. Just to make sure, when you switch your user agent, search for something that's likely to bring up results from news sites (like "royal baby") and click a result with a lightning icon, you aren't taken to an AMP page?

Sadly, I can't reproduce with curl, and yes, the URLs are unfortunately the same as the ones I posted. I know Google results tend to be super region specific, but when I search for "Google AMP", the second result is that register.co.uk article [Kill Google AMP before it kills the web](https://www.google.com/amp/s/www.theregister.co.uk/AMP/2017/05/19/open_source_insider_google_amp_bad_bad_bad/) I posted a link to above. I'll capture from this page, because I like the irony.

Console output:
![Screen Shot 2019-05-11 at 1 26 46 PM](https://user-images.githubusercontent.com/4484096/57573041-742d9380-73f0-11e9-8346-1c85a23ee1ea.png)

Worth noting—I began the log on the search results page. The first three entires in the log (through the first "powered by AMP") appear while I'm still on the search results page. Everything else appears when I click into the register.co.uk article.

Also worth noting: I was playing around myself, and if I modify the userscript to trigger `fuckOffAMP()` every ten seconds instead of just once, the redirect works. I don't really know what I'm talking about here, but if I had to guess, I'd say the problem is that the AMP article isn't considered a new page.

Here's the "outer" source of the page. Most of the actual content is in the iframe—that loads as the same code regardless of whether I go through Google search, so I didn't copy. https://gist.github.com/Wowfunhappy/c69f541f851c9013c7842786b8bc8ccd

**Comment by bentasker** [comment]
> I'm quite surprised you can't get AMP pages with an iOS user agent, I did a test in Firefox on Windows and it worked there too. 

After some tinkering, I think I found why.

For whatever reason, the Iphone user-agent within my switcher extension doesn't result in Google trying to serve AMP. However, switching to something else (like your UA value) also didn't result in AMP. Using the "correct" UA in a completely new session, however, did. I've not looked but I guess they're probably writing something into a session somewhere that marks whether you should be offered AMP or not, so that they only have to do the calculations once.

So, having got Google to offer me AMP, I still couldn't repro the issues your seeing.

I've gone over your screenshot, chased down a few possibilities, largely to no avail (amusingly, those Content Security Policy violations are nothing to do with any extensions, they just seem to have added a CSP that the cached content doesn't abide by).

> Also worth noting: I was playing around myself, and if I modify the userscript to trigger fuckOffAMP() every ten seconds instead of just once, the redirect works after a short delay. I don't really know what I'm talking about here, but if I had to guess, I'd say the problem is that the AMP article isn't considered a new page.

I've largely come up empty-handed, and that's as feasible an explanation as any. There is a line in your screenshot that suggests it is running (and deciding the page isn't AMP'd), but that might relate to some subresource instead. 

Realistically, I'm going to need to lay hands on a Mac (might be possible later in the week) to try and repro to troubleshoot further.

In the meantime, I've an alpha releases to change the detection just to see if it'll work for you and tie you over until I find a tidier fix. Might also help point me in the right direction.

So, could you try 2 things?

Change the require line to reference the alpha release
```
@require https://static1.bentasker.co.uk/adblock/anti-amp/v1.4.1a.js#sha384=M94A9wzmCjzLIZQdCFgEQrUd09raRfA+KvkUqaUfOnfvz8LwElYxWYqaQ+aPjrga
```
That'll be a little more expensive to run than the other versions, as it'll scan the DOM looking for iframes and then seeing if any reference cdn.ampproject.

Once you've seen if that works, it'd be worth editing the userscript to effectively revert commit 9701149

Rather than
```
window.addEventListener ("load", triggerAMPCheck, false);

function triggerAMPCheck () {
    fuckOffAMP();
}
```
Just have

```
fuckOffAMP();
```
Which removes the dependance on the `load` event (as you say, perhaps Safari isn't considering it a new page and therefore there's no `load`).

Be aware of the reason that was removed though - without the eventlistener, it'll trigger against every subrequest. It shouldn't break anything, but will quite happily eat your phone's battery. Definitely not a long-term fix, but should point us in the right direction.

If that works, then it'd be worth updating one more time so that you're no longer referencing v.1.4.1a just to verify they work independently (and save yourself the overhead of that DOM lookup).

**Comment by Wowfunhappy** [comment]
Thanks again, I really appreciate all the time you're putting into this!

> Change the require line to reference the alpha release
That'll be a little more expensive to run than the other versions, as it'll scan the DOM looking for iframes and then seeing if any reference cdn.ampproject.

This does not work, and actually seems to regress—I am no longer taken to the non-AMP article when I reload.

>  it'd be worth editing the userscript to effectively revert commit 9701149

This does not cause any change in behavior versus using the event listener.

**Comment by bentasker** [comment]
OK, so I've laid hands on a Mac, and can now see what's going on

>  I don't really know what I'm talking about here, but if I had to guess, I'd say the problem is that the AMP article isn't considered a new page.

Bang on the money :)

What Google are doing when you click the link, is rather than directing your browser to a new page, is rewriting the page in JS (to essentially just blank it and write in the iframe of AMP CDN). They're then rewriting the address bar using javascript (I really, really hope that there's a special place reserved in hell for people that do that).

So, as a result, the hook never fires.

When you reload the page, the browser reloads the address that you see in the address bar (i.e. the rewritten one), so this *is* a page load (the first to that address) and the hook triggers as a result.

Google's javascript tends to be heavily obfuscated so I didn't bother trying to reverse engineer it too much.

Their functionality seems to rely on a bunch of attributes that they append to the link anchor though, so what I've done is created a new short user-script specifically to deal with Google search results. Essentially it looks for AMP results (as efficiently as possible) and then strips off the attributes they check for in their JS to decide whether to use their own cache. It also rewrites the link `href` to send you direct to the site's non-AMP representation (there is currently a [dirty hack](https://projects.bentasker.co.uk/jira_projects/browse/MISC-29.html#comment2512645) here though)

So, if you install and enable this script - https://github.com/bentasker/RemoveAMP/raw/master/greasemonkey_hook_googlesearch.user.js - and then test again, hopefully it should work.

It could definitely do with refining, but it does at least seem to work on my test rig.

Let me know, and if it works for you I'll tag a release

**Comment by Wowfunhappy** [comment]
There we go, works perfectly now! Thank you so much!

**Comment by bentasker** [comment]
Awesome, thanks for confirming.

I've just rolled v1.6.1 with the iframe detection removed (as it was causing you issues when we tested).

Thanks for all the input

**Comment by Wowfunhappy** [comment]
Okay, one other little niggle with this—if you click "more" to load additional search results, any further results below that point still take you to the AMP page.

Not wanting to bother you again, I hacked around a bit, and found a solution that seems to work:

```
var timesRan = 0;
function AMPCheck() {
    var da;
    var bads = ['data-amp','data-amp-cur','data-amp-title','data-amp-vgi','ping'];
    var eles = document.getElementsByClassName('amp_r');
    for (var i=0; i<eles.length; i++){
        if (eles[i].tagName.toLowerCase() != 'a'){
            continue;
        }

        da = eles[i].getAttribute('data-amp-cur');
        if (! da){
            continue;
        }

        if (!da.includes('?')){
            da += '?';
        }
    
        eles[i].href = da;

        for (n=0; n<bads.length; n++){
            eles[i].removeAttribute(bads[n]);
        }
    }
    console.log("AMP check has run " + timesRan);
    timesRan++;
}

window.addEventListener ("load", function(){
    AMPCheck();
    document.addEventListener("DOMNodeInserted", triggerAMPCheck, false);
}, false);
```

Basically:
1. Put the main code into a function `AMPCheck()`
2. Wait for the page to load, then trigger `AMPCheck()` once.
3. Repeat `AMPCheck()` any time the `DOMNodeInserted ` event fires.

(The `timesRan` code was just for me to check how often the function was running, and can be removed.)

This solution runs `AMPCheck()` many more times than would be ideal. I've observed `DOMNodeInserted` firing anywhere between zero  and 120 times on initial page load, and then between 4 and 70 additional times whenever the "more" button is clicked. Still, I prefer this to throwing the function in a loop that runs every ten seconds. I don't actually know what I'm doing, so you may have something better. :)

**Comment by Wowfunhappy** [comment]
Okay, much improved version of this: https://gist.github.com/Wowfunhappy/baf5e55ea7f2b5e11fd19d51d3893175

I added a debounce (shamelessly stolen from https://davidwalsh.name/javascript-debounce-function) so that AMPCheck() will never run more than once per half second. This actually seems to work perfectly—at least on my machine, the function runs exactly once per press of the "more" button.

**Comment by bentasker** [comment]
Nice.

Fancy raising a pull request so the commit has your name against your work? :)
